### ISSUE TITLE
while loop

### ISSUE THREAD

**Issue by isomorphisms** [motemen/gore#102]
I'm not sure if this is my fault or gore's, but I believe I am typing the same code into `go run` and `gore`:

```
func power(base int, exponen tint) int {
	monad := 1
	for exponent > 0 {
		monad *= base
		exponent--
		}
	return monad
	}
```

I think gore is thinking there is an unmatched `(` or `{` in here, but `go run` disagrees.

HTH

**Comment by itchyny** [comment]
The issue is resolved now. Note that you have a typo in the first line.
