### ISSUE TITLE
Make REPL fun again

### ISSUE THREAD

**Issue by scls19fr** [motemen/gore#104]
Hello,

I'm a Julia user currently trying Go.

Julia REPL looks nice with ASCII art

![capture d ecran 2018-11-24 a 21 37 02](https://user-images.githubusercontent.com/109167/48972737-8332ac00-f031-11e8-913f-bf51dfc1327b.png)

compared to Gore:

![capture d ecran 2018-11-24 a 21 37 45](https://user-images.githubusercontent.com/109167/48972869-d148af00-f033-11e8-97ef-1e8f124d2013.png)

I noticed
https://gist.github.com/belbomemo/b5e7dad10fa567a5fe8a from @belbomemo
could be a nice ASCII art for Gore
but some other could be find using
https://www.google.fr/search?q=gopher+golang+ascii

Here is a possible prompt:

```
         ,_---~~~~~----._           |
  _,,_,*^____      _____``*g*\"*,   |  gore
 / __/ /'     ^.  /      \ ^@q   f  |  Yet another Go REPL
[  @f | @))    |  | @))   l  0 _/   |  
 \`/   \~____ / __ \_____/    \     |  version 0.3.0
  |           _l__l_           I    |  
  }          [______]           I   |  :help for help
  ]            | | |            |   |  
  ]             ~ ~             |   |
  |                            |    |  The Go Programming Language
   |                           |    |  version x.y.z
gore> 
```

I hope you will consider this highly important enhancement request to make REPL fun again ;-)

Kind regards

**Comment by itchyny** [comment]
Sorry but I don't think ascii art message is not worth implementation. Note that many repls prints only the interpreter versions like python and ghci, and irb prints nothing, they are simple that we can quickly start inputting what we want to execute without being bothered by the startup message.
