### ISSUE TITLE
astutil gone, cannot build

### ISSUE THREAD

**Issue by kokizzu** [motemen/gore#12]
Same issues with https://github.com/vektra/mockery/issues/6

```
commands.go:17:2: cannot find package "golang.org/x/tools/go/ast/astutil" in any of:
        /usr/lib/go/src/golang.org/x/tools/go/ast/astutil (from $GOROOT)
        /home/asd/Dropbox/go/src/golang.org/x/tools/go/ast/astutil (from $GOPATH)
```

**Comment by kokizzu** [comment]
workaround:

```
mkdir $GOPATH/src/golang.org/x/tools/go/ast
$GOPATH/src/golang.org/x/tools/astutil $GOPATH/src/golang.org/x/tools/go/ast
```

**Comment by motemen** [comment]
It does not seem the same problem as you mentioned, since golang.org/x/tools/go/ast/astutil [does exist](http://golang.org/x/tools/go/ast/astutil). Maybe you should run `go get golang.org/x/tools/go/ast/astutil`?

**Comment by kokizzu** [comment]
yes I have run that command, but still got the same error:
```
Fetching https://golang.org/x/tools/go/ast/astutil?go-get=1
Parsing meta tags from https://golang.org/x/tools/go/ast/astutil?go-get=1
(status code 200)
get "golang.org/x/tools/go/ast/astutil?": found meta tag
main.metaImport{Prefix:"golang.org/x/tools", VCS:"git", RepoRoot:"
https://go.googlesource.com/tools"} at
https://golang.org/x/tools/go/ast/astutil?go-get=1
get "golang.org/x/tools/go/ast/astutil?": verifying non-authoritative meta
tag
Fetching https://golang.org/x/tools?go-get=1
Parsing meta tags from https://golang.org/x/tools?go-get=1 (status code 200)
golang.org/x/tools (download)
package golang.org/x/tools/go/ast/astutil?: /home/asd/Dropbox/go/src/
golang.org/x/tools exists but /home/asd/Dropbox/go/src/
golang.org/x/tools/.git does not - stale checkout?
```

I've tried to remove the `x/tools` directory and fetch it again, but the
error still the same.

-- 
Regards,
Kiswono P
GB

**Comment by motemen** [comment]
Looks strange, cannot reproduce. Did you removed the golang.org/x/tools directory itself, not only its children? Maybe you can set $GOPATH to another value to try it on a fresh environment.

As of now, this issue seems not of gore, but your environment.

**Comment by kokizzu** [comment]
yea, maybe I'll upgrade to 1.4.2, it seems only <1.4.1 has this problem.

**Comment by motemen** [comment]
As I'm using go1.4.1 and having confirmed that gore builds on Go 1.3 on Docker, I think Go version is not the problem.

**Comment by kokizzu** [comment]
Hmm.. nevermind, got it working now.. https://stackoverflow.com/questions/28689700

**Comment by motemen** [comment]
Good to hear :smile:

**Comment by RylanSchaeffer** [comment]
@kokizzu how did you get it working?

**Comment by kokizzu** [comment]
@RylanSchaeffer it's on that stackoverflow link '__') i wrote my solution there.. but that's like 4 years ago, idk if it's working on 1.10+
