### ISSUE TITLE
Feature request: ctrl/alt+backspace to remove 1 word

### ISSUE THREAD

**Issue by kokizzu** [motemen/gore#13]
Just like bash's shortcut to remove last typed word (alt+backspace)

**Comment by ches** [comment]
This could probably be a request for https://github.com/peterh/liner which gore uses. `Ctrl-w` currently achieves this effect, see the project README for other support key bindings.

**Comment by ches** [comment]
Related: #41

**Comment by itchyny** [comment]
We can use ctrl-w for this, so closing.
