### ISSUE TITLE
How to setup pretty printing?

### ISSUE THREAD

**Issue by midnightrun** [motemen/gore#144]
Hi,
I just found out about `gore` and I like to have a REPL, so thanks for taking the time creating this project.

I just `go get` `gore` and `pp` but when I run the example code like in our gif within the README I dont get pretty printing somehow.

```shell
➜ gore
gore version 0.4.0  :help for help
gore> :import encoding/json
gore> b, err := json.Marshal(nil)
[]byte{0x6e, 0x75, 0x6c, 0x6c}
<nil>
gore>
``` 

There is no color or nice structure just the flat output.

System
- macOS
- Therm x zsh.
- go version go1.12.1 darwin/amd64

Thanks!

**Comment by itchyny** [comment]
This is weird and unreproducible. Make sure

- go get again and check the behavior
- there's Go module files at current directory or not. Some unintended behavior is found around go modules.
- `echo "package main\nimport \"github.com/k0kubun/pp\"\nfunc main() { pp.Println(map[string]string{\"hello\":\"world\"}) }" > /tmp/main.go && go run /tmp/main.go` prints the map successfully

<img width="570" alt="Screen Shot 2019-03-27 at 14 16 50" src="https://user-images.githubusercontent.com/375258/55052086-01b06080-509b-11e9-90ca-1446d612ba02.png">

**Comment by midnightrun** [comment]
Hi,
i checked everything.

1) When running the Docker container like you everything is working.
2) _go get again and check the behavior_: Did everything from scratch same problem occurs, no formatting.
3) _go.mod problem_: No mod file, I am running it at `/`
4) Your `echo` example is working for me

Thanks for taking the time :)

**Comment by itchyny** [comment]
Hmm, do you set GOPATH environment variable? And `ls $GOPATH/src/github.com/k0kubun/pp` works?

**Comment by midnightrun** [comment]
Hi,
it is working. I set `GO111MODULE` to on. So my `go get` wasn't getting the src into my path. I applied `go get` again for both packages and now it is working like a charme. Thank you!

**Comment by itchyny** [comment]
Okay, I'm wondering adding `GO111MODULE=off` before go get commands in installation instruction...
