### ISSUE TITLE
cannot execute main()

### ISSUE THREAD

**Issue by luochen1990** [motemen/gore#150]
Reproduce:
---

the file `hello.go`

```
package main

import "fmt"

func main() {
    fmt.Println("Hello, Go")
}
```

in gore:
```
gore -context hello.go

gore> main()

....
```

Expected:
---

main() works correctly and "Hello, Go" is printed

Observed:
---

a lot of magic code is printed.

**Comment by itchyny** [comment]
This is an expected behavior, you can't run main() within gore. Currently gore generates a go file and just runs it. See https://github.com/motemen/gore#faqcaveats.
