### ISSUE TITLE
Can't execute after update

### ISSUE THREAD

**Issue by gkm2164** [motemen/gore#152]
I installed with `go get... ` and I had used well whatever update happen.

But yesterday, there was a lot of update when I typed ```gore``` and it is unable to run ```main()```
Below is an error message.
```
$> gore
go run: cannot run non-main package
````

**Comment by itchyny** [comment]
What do you mean by update? Update of gore version or of what?

**Comment by gkm2164** [comment]
Sorry for an ambiguous use of word.
It was a lot of updates including "golang/... /sys/syscall..." related updates.

**Comment by gkm2164** [comment]
I'm really sorry.. it was by an alias that I set ... stupid :( I will remove this ticket soon.
