### ISSUE TITLE
Change working directory back to original directory

### ISSUE THREAD

**Issue by eikenb** [motemen/gore#156]
```
[~]pwd
/home/jae/tmp
[~]gore
gore version 0.4.1  :help for help
gore> :import os
gore> os.Getwd()
"/tmp/gore-349575424"
<nil>
gore> 
```
When gore starts up it has the working directory of a temp directory. It'd be nice if it switched back to the original directory after startup.

Maybe check the environment for PWD and change to that after startup?  Both bash and zsh set it, and it keeps the pre-gore value.

Thanks.

**Comment by itchyny** [comment]
I believe moving to the temporary directory is necessary not to mess up the go.mod file in the current project.

**Comment by eikenb** [comment]
Hadn't thought of that. I tend to use gore outside of projects as a quick way to test something. This came up as I was wanting to test filesystem calls and had created a set of dirs/files to test under the original directory. 

How about a new :command, ":cd <path>"?

**Comment by eikenb** [comment]
Found the issue/PR about why the temp directory... #147

**Comment by eikenb** [comment]
I'm going to close this issue for now as there is a good reason for the existing behavior and there is a workaround... `import os; os.Chdir(<path>)`.

**Comment by supercheetah** [comment]
Can this be re-opened?  The workaround doesn't work if the temp directory doesn't have execute permissions, and the reason for changing directory would be that (or if this should be a new bug, I can open one for that too):

```
gore> os.Chdir("C:\\Users\\myusername\\go\\temp")
fork/exec C:\Users\myusername\AppData\Local\Temp\go-build2952805507\b001\exe\gore_session.exe: This program is blocked by group policy. For more information, contact your system administrator.
```
