### ISSUE TITLE
Can not use "\" within regexp within gore

### ISSUE THREAD

**Issue by icewire314** [motemen/gore#157]
If a regexp compile statement is issued without a "\", things are fine but ...

r, _ := regexp.Compile("\s")

causes the REPL to go into a "..." multiline mode and does not work correctly.
It would have been great to try out regexp within gore to get a better understanding of its commands.

**Comment by itchyny** [comment]
You cannot write that in Go code neither. Use `"\\s"` or ``` `\s` ```. This is not a problem of gore.

**Comment by itchyny** [comment]
Yeah, gore supports multi-line input so gore cannot distinguish the compilation error due to some part of multi-line input or invalid syntax.
