### ISSUE TITLE
backslashes break gore's scanner

### ISSUE THREAD

**Issue by samertm** [motemen/gore#17]
```
gore> h\ello<enter>
..... <enter>
..... <ctrl-d>
gore> hello\t<enter>
..... <enter>
..... <ctrl-d>
gore> he\\llo<enter>
..... <enter>
.....
```

Only a couple escape sequences are valid: https://golang.org/ref/spec#Rune_literals

**Comment by motemen** [comment]
It's because gore enters line-continuation mode if it fails to parse input. What is your expected behavior?

As you may already know, for string literals you must surround them by `"`s:

~~~
gore> "hello\t"
"hello\t"
~~~

**Comment by samertm** [comment]
> It's because gore enters line-continuation mode if it fails to parse input. What is your expected behavior?

That explains it :P I was expecting an error.

**Comment by motemen** [comment]
Got the point. I have currently no idea with this problem.

**Comment by samertm** [comment]
The reason I ask is because I'm writing a CLI app too, and I wanted to see how you handle backslashes. For my app, all backslashes outside of quotes are literals, and backslashes within quotes always escape the character after, which you can see [here](https://sourcegraph.com/sourcegraph/srclib@c2dfaa0fe1166e450e7d5ff61f0b09371d1486d4/.GoPackage/sourcegraph.com/sourcegraph/srclib/src/.def/lexer/emitValue). Where do you parse CLI input?

**Comment by motemen** [comment]
One night passed and I think we can use go/scanner to detect illegal characters in the source, though I have not tested it.

FYI, I'm parsing input using go/parser.ParseFile [here](https://github.com/motemen/gore/blob/cbec22b/main.go#L278) and if the error was go/scanner.ErrorList, gore prompts to continue line [here](https://github.com/motemen/gore/blob/cbec22b/main.go#L383-385).

**Comment by itchyny** [comment]
This issue is resolved now.
