### ISSUE TITLE
Error occurs: `Unexpected package creation during export data loading`

### ISSUE THREAD

**Issue by vsajip** [motemen/gore#172]
```
$ gore
gore version 0.5.0  :help for help
gore> :import config
gore> :print
package main

import (
    "github.com/k0kubun/pp"
    "config"
)

func __gore_p(xs ...interface{}) {
    for _, x := range xs {
        pp.Println(x)
    }
}
func main() {}

gore> cfg := config.NewConfig()
2020/01/17 18:53:02 Unexpected package creation during export data loading
```
How can I progress?

**Comment by vsajip** [comment]
Also:
```
$ gore
gore version 0.5.0  :help for help
gore> :import config
gore> config.ISO_DATETIME_PATTERN
2020/01/17 18:56:37 Unexpected package creation during export data loading
```

**Comment by itchyny** [comment]
I've encountered this while I was to updating the `golang.org/x/tools` package. Can you install with `env GO111MODULE=on go get github.com/motemen/gore/cmd/gore` and try again?

**Comment by itchyny** [comment]
https://go-review.googlesource.com/c/tools/+/214943 https://github.com/golang/tools/commit/84cebe10344f1cd161b47a7087b7979c67beab95 is related to this

**Comment by itchyny** [comment]
Now that this issue is fixed, please update gore.

**Comment by vsajip** [comment]
Thanks for the quick response. It now gets past this, but fails as per #174 now.
