### ISSUE TITLE
Failure with 'malformed module path "XXX": missing dot in first path element'

### ISSUE THREAD

**Issue by vsajip** [motemen/gore#174]
I have a `config` module available on `GOPATH`. I verify this by running the following program:
```
package main

import (
    "config"
    "fmt"
)

func main() {
    _ = config.NewConfig()
    fmt.Printf("OK\n")
}

```

When run, this prints as expected:
```
$ go run main.go
OK
```
However, with `gore`, I get an error:

```
$ gore
gore version 0.5.0  :help for help
gore> :import config
gore> :import fmt
gore> _ = config.NewConfig()
cannot load config: malformed module path "config": missing dot in first path element
gore> fmt.Printf("OK\n")
cannot load config: malformed module path "config": missing dot in first path element
gore> :print
package main

import (
    "github.com/k0kubun/pp"
    "fmt"
    "config"
)

func __gore_p(xs ...interface{}) {
    for _, x := range xs {
        pp.Println(x)
    }
}
func main() { _ = config.NewConfig(); _, _ = fmt.Printf("OK\n") }

gore> 
```
Am I doing something wrong? I just updated `gore` after running into #172 and I've tried updating `gore` both with `GO111MODULE=on` and without.

**Comment by itchyny** [comment]
Can you use it from starting gore at the config directory?

**Comment by vsajip** [comment]
> Can you use it from starting gore at the config directory?

Of course, I tried that before creating this issue. The result is the same error message :disappointed:

**Comment by itchyny** [comment]
Where do you place the config package? Under `$GOPATH/src/config/`? Also I want to know your config package supports go modules or not.

**Comment by vsajip** [comment]
Here's a test with just a single `config.go` file in the current directory:
```
~/projects/scratch/go  $ ls
config.go
~/projects/scratch/go  $ more config.go 
package config

type Any interface{}

func NewConfig() Any {
    return nil
}
~/projects/scratch/go  $ gore
gore version 0.5.0  :help for help
gore> :import config
gore> _ = config.NewConfig()
cannot load config: malformed module path "config": missing dot in first path element
gore> 
```

Now, copy `config.go` to a `src/config` subdirectory and create a `main.go`:
```
~/projects/scratch/go  $ mkdir -p src/config
~/projects/scratch/go  $ cp config.go src/config/
~/projects/scratch/go  $ cat main.go
package main

import (
    "config"
    "fmt"
)

func main() {
    c := config.NewConfig()
    fmt.Printf("%v\n", c)
}
~/projects/scratch/go  $ GOPATH=$PWD go run main.go
<nil>
```
Try gore again:
```
~/projects/scratch/go  $ GOPATH=$PWD gore
gore version 0.5.0  :help for help
gore> :import config
gore> _ = config.NewConfig()
cannot load config: malformed module path "config": missing dot in first path element
gore> 
```

**Comment by itchyny** [comment]
Try `cd $GOPATH/src/config; go mod init config; gore`.

**Comment by itchyny** [comment]
I believe that go assumes the directories under $GOPATH/src/ are the host name where the code is distributed, which the message `missing dot in first path element` means.

**Comment by vsajip** [comment]
> Try cd $GOPATH/src/config; go mod init config; gore

OK, with that, the error goes away. Thanks. But does this mean that old-style pre-Go-1.11 code on GOPATH isn't supported by gore?

**Comment by itchyny** [comment]
> But does this mean that old-style pre-Go-1.11 code on GOPATH isn't supported by gore?

True.

- Go modules are widely accepted by the community and not supporting this was a fatal issue fore gore.
  - There's no reason not to place go.mod file in a project. This is backward compatible.
- It's easy to upgrade the Go version to the latest 1.x.
- Supporting Go modules was a long-wish issue and it resolves various problems.
  - We don't need `go get` to test quickly the remote repository.
  - We don't need go get pretty printer package anymore.
  - Complete import candidates from go.mod.
  - It is more important to improve the usability for public repository rather than local repository.
- But this disabled loading package from GOPATH.
  - We can still use gore with local module by starting gore at the project directory, as long as it support go modules. Supporting go modules is much more important than supporting old-style local project.

**Comment by vsajip** [comment]
Oh, I agree about the benefits that Go modules provide. I was just trying to understand gore's limitations! Thanks for your quick response and helpful comments.
