### ISSUE TITLE
Function is called every time when use -context option.

### ISSUE THREAD

**Issue by rennnosuke** [motemen/gore#185]
Hi,

When `.go` file is specified with `-context` option, and once function `f()` on `.go` file is called,
 it is called every time even if it is not inputed `f()`.

ex.

#### env
OS : Mac OS Catalina 10.16.3
Runtime : Go 1.13.6

#### context.go

```go
package main

import "fmt"

func start() {
	fmt.Println("exec context.go .")
}
```

```
$ gore -context context.go
gore version 0.5.0  :help for help
added file context.go
gore> start()
exec context.go .
gore> fmt.Println("on REPL.")
exec context.go . // called 'start()'  again implicitly. 
on REPL.
9
nil
gore>
```

Thanks.

**Comment by itchyny** [comment]
This is a limitation due to the fact that gore is not a real read-eval-print loop tool. See https://github.com/motemen/gore#faqcaveats, #67.
