### ISSUE TITLE
hanging reference 

### ISSUE THREAD

**Issue by aidylewis** [motemen/gore#19]
Not sure why the side effect of fmt.Printf should appear when I declare a variable.

```sh
gore> :import "fmt"
gore> fmt.Printf("foo\n")
foo
4
nil
gore> var i int
foo
gore> 
```

**Comment by motemen** [comment]
Thanks, this is an open issue as noted in [Caveats](https://github.com/motemen/gore#caveats), as gore invokes `go run` for each time you add a code snippet.
