### ISSUE TITLE
Suspend with Ctrl-Z

### ISSUE THREAD

**Issue by santosh** [motemen/gore#190]
```
$ gore --version
gore 0.5.0 (rev: HEAD/go1.14.3)

$ uname -a
Linux fedora32 5.7.8-200.fc32.x86_64 #1 SMP Thu Jul 9 14:34:51 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

Normally when I run any program from the terminal, I can suspend it with C-z. But it does not seem to work with gore. Is it possible to implement this?

**Comment by itchyny** [comment]
`gore` depends on [`liner`](https://github.com/peterh/liner) package, and it seems it is impossible for now https://github.com/peterh/liner/issues/131.
