### ISSUE TITLE
copied text ends wrap into __gore_p

### ISSUE THREAD

**Issue by juanolon** [motemen/gore#20]
hello,
nice work with gore. i would like to be able to copy text from vim directly into gore. but when i copy a text like this 
`pam := make([][]int, h)`
from vim into the gore command line, ends like:
`gore> __gore_p(pam := make([][]int, h)`

i can only image of the tab being scape or something..
can you help me here?
thanks

**Comment by motemen** [comment]
Thank you for reporting. Looks odd, I'll look into this. (I imagine the problem coming from `github.com/peterh/liner`)

**Comment by itchyny** [comment]
This issue is not reproducible anymore so closing.
