### ISSUE TITLE
gore failed on MacOS 10.15.6 with go 1.15.7

### ISSUE THREAD

**Issue by angusdavisadobe** [motemen/gore#201]
~  > go version
go version go1.15.7 darwin/amd64

~  > gore
gore: could not load 'fmt' package: err: exit status 1: stderr: build flag -mod=mod only valid when using modules

**Comment by itchyny** [comment]
I cannot reproduce. I double checked by reinstalling and it works fine.
```bash
❯ go version
go version go1.15.7 darwin/amd64

❯ sw_vers -productVersion
11.1

❯ go clean -modcache

❯ go get github.com/motemen/gore/cmd/gore

❯ gore
gore version 0.5.2  :help for help
gore> 42
42
gore>
```

**Comment by milad-abbasi** [comment]
Running `go clean -modcache` command solved the problem for me.

**Comment by angusdavisadobe** [comment]
Thanks for the reply but  'go clean -modcache' didn't work for me.

> sw_vers -productVersion
10.15.6
> go clean -modcache
> go get github.com/motemen/gore/cmd/gore
> gore
gore: could not load 'fmt' package: err: exit status 1: stderr: build flag -mod=mod only valid when using modules

**Comment by itchyny** [comment]
Try `export GO111MODULE=on`.

**Comment by angusdavisadobe** [comment]
sadly, setting GO111MODULE=on didn't work. gave same error

**Comment by itchyny** [comment]
How about `go get -u github.com/motemen/gore/cmd/gore`?

**Comment by itchyny** [comment]
Did you `go get github.com/motemen/gore/cmd/gore` after `export GO111MODULE=on`?

**Comment by angusdavisadobe** [comment]
yes. I uninstalled  gore with 
`go clean -i github.com/motemen/gore/cmd/gore
I then set `export GO111MODULE=on` and  then re-installed gore.
That worked.
