### ISSUE TITLE
Strange print behaviour? :)

### ISSUE THREAD

**Issue by fgimian** [motemen/gore#28]
Hey there Hiroshi, great job on gore :smile: 

I'm seeing a strange behaviour that I wanted to run by you.  I just installed gore the 3 recommendations today and am seeing the following behaviour when I use println multiple times:

```
gore version 0.2.1  :help for help
gore> :import fmt
gore> fmt.Println("Hello, world")
Hello, world
13
nil
gore> fmt.Println("Hello, world")
Hello, world
Hello, world
13
nil
gore> fmt.Println("Hello, world")
Hello, world
Hello, world
Hello, world
13
nil
```

Things I didn't expect:

* The 13 and nil outputs, what are they?
* The multiple repetition of lines after the first attempt

Am I doing something incorrectly?

Cheers
Fotis

**Comment by motemen** [comment]
Thanks,

> The 13 and nil outputs, what are they?

They are the results of [`fmt.Println`](http://godoc.org/fmt#Println), which are the bytes written and the error.

> The multiple repetition of lines after the first attempt

This is an open issue as noted in [Caveats in README](https://github.com/motemen/gore#caveats). As gore invokes `go run` for each input, any code with side effects will cause side effects repeatedly. For printing values, mostly you will not need to print them as gore itself prints result values of an expression.
