### ISSUE TITLE
Installation does not provide 'gore' executable

### ISSUE THREAD

**Issue by adsteel** [motemen/gore#31]
This is all on a Mac, OS 10.10.3.

```
$ go version
go version go1.4.2 darwin/386
$ go get github.com/motemen/gore
// reload terminal
$ gore
-bash: gore: command not found
```

Am I missing something?

**Comment by bricker** [comment]
@adsteel make sure `$GOPATH/bin` is in your $PATH. For example, `/Users/adsteel/go/bin`

**Comment by adsteel** [comment]
I'm sure that's it. I just broke my terminal trying to do it, but I'll reopen this if this doesn't solve it. Thank you!
