### ISSUE TITLE
Mention Ctrl-D to exit in :help

### ISSUE THREAD

**Issue by stanim** [motemen/gore#35]
I had to look up the readme at github to see how to exit. These two options exist (if you agree it is an issue):
- mention it when `:help` is displayed
- display the following when gore starts:
```
gore version 0.2.2  :help for help  Ctrl-D to exit
```

**Comment by motemen** [comment]
Thanks, closing by adding `:quit` command. (Mentioned in `:help`)

**Comment by stanim** [comment]
Great. Thanks!
