### ISSUE TITLE
"const" broken

### ISSUE THREAD

**Issue by nburns** [motemen/gore#39]
Currently I can't define more than one const in a declaration list

```
gore version 0.2.4  :help for help
gore> const (
..... a = iota
..... b = iota
..... c = iota
..... )
gore> fmt.Println(a)
0
2
<nil>
gore> fmt.Println(b)
# command-line-arguments
/var/folders/n7/lmdrbrks7zqd2ns7rwj8rjf80000gn/T/131512700/gore_session.go:13: undefined: b
error: exit status 2
exit status 2
gore> fmt.Println(c)
# command-line-arguments
/var/folders/n7/lmdrbrks7zqd2ns7rwj8rjf80000gn/T/131512700/gore_session.go:13: undefined: c
error: exit status 2
exit status 2
gore>
```

**Comment by nburns** [comment]
I really appreciate gore btw. Im just getting into go, and I find it very helpful.

I just don't know if I'm doing something wrong or if this case is a bug. The following runs as expected with "go run" (it outputs 0 1 2)

```
package main

import "fmt"

func main() {
	const (
		a = iota
		b = iota
		c = iota
	)
	fmt.Println(a)
	fmt.Println(b)
	fmt.Println(c)
}
```

**Comment by motemen** [comment]
Thanks, that's strange. I've just created [regression test](https://github.com/motemen/gore/commit/96a24312f005132b094d33ff9901809eb807eda9), will invest it shortly.
