### ISSUE TITLE
Programmatic API

### ISSUE THREAD

**Issue by amasad** [motemen/gore#4]
Does gore have a programmatic API? I recently added Go to repl.it but it's not really running as a REPL. You can just run the code http://repl.it/languages/Go

With gore, it would be epic. Are there instructions on how to use it as a library?

**Comment by motemen** [comment]
Currently gore does not provide APIs, but it seems good to implement one.

I'll include it in the roadmap and it may take a long time to do it. Please be patient, thanks!

**Comment by DevelopSMM** [comment]
Echoing support for this.  I'm looking into the possibility of using Golang for video games.  It seems a perfect fit, except for garbage collection.  Having an in-game REPL console would be great.
