### ISSUE TITLE
__gore_p( inserted into multiline input

### ISSUE THREAD

**Issue by willfaught** [motemen/gore#40]
End a line with a left parenthesis, enter a new line, then enter tab to indent:

    $ gore
    gore version 0.2.2  :help for help
    gore> func(x int){}(
    ..... __gore_p(

Instead of a tab, `__gore_p(` is inserted where the cursor was, and the cursor is moved after the insertion.

Looks related to #20.

**Comment by willfaught** [comment]
Verified in 0.2.4 too.

**Comment by motemen** [comment]
Thanks for your issue.

`tab` is used for code completion, so it seems the implicitly declared function `__gore_p` appeared as completion candidate. I see some problems here:

- `__gore_p` should not appear in the completion (#45)
- After `func (x int){}(\n`, the prompt should be indented (#46)
- If no code was typed, `tab` should behave as indentation, which depends on `peterh/liner`'s API (#47)

Issued as separated problems, so I'm closing this issue now. Thanks!
