### ISSUE TITLE
Full readline support

### ISSUE THREAD

**Issue by willfaught** [motemen/gore#41]
It would be great to be able to use Alt-B and Alt-F to skip backward and forward by a word.

**Comment by motemen** [comment]
Thanks, the readline behavior depends on `github.com/peterh/liner`. If there's any other readline library that works on linux/darwin/windows which gore supports, it may be worth considering.

**Comment by willfaught** [comment]
github.com/bobappleyard/readline is a set of bindings to the GNU Readline library, which supports Linux, and OS X with Command Line Tools, and Windows with Cygwin. I guess that's more limited.

**Comment by chzyer** [comment]
@motemen , Hi~ Would you mind considering https://github.com/chzyer/readline , supports linux/darwin/windows too with more features. :)

**Comment by motemen** [comment]
Thanks both, gonna make a try on using chzyer/readline, which seems good.

**Comment by chzyer** [comment]
@motemen Thanks! Please let me know if you have any suggestions.
:)

**Comment by itchyny** [comment]
Years passed and now https://github.com/chzyer/readline is no more active project so maybe we will continue using https://github.com/peterh/liner. Also, skipping words works already. I confirmed that option-← works on Terminal.app, so closing. (If you can't get it work on iTerm2, see https://apple.stackexchange.com/questions/136928).
