### ISSUE TITLE
Build fails.

### ISSUE THREAD

**Issue by qazwsxpawel** [motemen/gore#43]
Hi I've tried go-getting gore (`go get github.com/motemen/gore`) and it doesn't build: 
 
```
Dev/go/src/github.com/motemen/gore/commands.go:251: too many arguments in call to mainScope.LookupParent
```

Cheers!

**Comment by syohex** [comment]
`mainScope.LookupParent` signature was changed. Please upgrade `golang.org/x/tools/go/types`. See #23.

**Comment by motemen** [comment]
Thanks, as @syohex says, you need update `tools/go/types` by `go get -u golang.org/x/tools/go/types`.
