### ISSUE TITLE
Multiple values printed for one expression

### ISSUE THREAD

**Issue by willfaught** [motemen/gore#49]
It seems like both the `time.Now()` and `.UTC()` values get printed:

    $ gore -autoimport
    gore> time.Now().UTC()
    time.Time{sec:63576820296, nsec:236228056, loc:(*time.Location)(0x21b860)}2015-09-02 19:51:36 UTC

Also, strangely, the formats are different.

**Comment by ches** [comment]
This looks like output from the `github.com/davecgh/go-spew` pretty printer that gore supports if it is available. Perhaps there could be a flag or some type of config to specify one or opt out of loading a pretty printer?

**Comment by willfaught** [comment]
It'd be nice if it always pretty printed values. `%#v` sucks for pointer values.

**Comment by motemen** [comment]
I am not sure why you got this output. (Maybe your local go-spew source code somewhat broken?)

Would you mind if I ask you to:

- Run `:print` to show the session's full source code
- `(cd "$(go list -f '{{.Dir}}' github.com/davecgh/go-spew/spew)" && git status; git rev-parse HEAD)` to obtain the local state of go-spew code

these will help, thanks.

**Comment by willfaught** [comment]
I don't have github.com/davecgh/go-spew/spew installed.

I don't seem to be able to reproduce the problem now, though (v0.2.5)...
