### ISSUE TITLE
Exit from the REPL

### ISSUE THREAD

**Issue by yelinaung** [motemen/gore#5]
First of all, thanks a lot for this awesome stuff. Absolutely love it.
I am sorry as this is a pretty basic question. I don't know how I can exit from REPL. 
It seems `Ctrl+C`, `exit` and `quit` don't work and I can't find anywhere in the code, `:help` or in README about it. 

Here's what happened what I tried `quit`

```
gore version 0.0.0  :help for help
gore> quit
# command-line-arguments
/var/folders/21/6n2vjp8d5q5czng49nh3h4240000gn/T/627674172/gore_session.go:12: undefined: quit
error: exit status 2
exit status 2
gore>
```

**Comment by jpudney** [comment]
I managed to exit with `Ctrl+d` if that helps?

**Comment by yelinaung** [comment]
Yes it works. Thanks! Should I close this one now?

**Comment by motemen** [comment]
Thank you for reporting.

I think it's missing from the doc. I made an issue for documenting this, closing this issue for now.
