### ISSUE TITLE
can't import time

### ISSUE THREAD

**Issue by tejasmanohar** [motemen/gore#52]
Tejass-MacBook-Pro:backend tejas$ gore
gore version 0.2.5  :help for help
gore> :import time
gore> time
# command-line-arguments
/var/folders/mr/qvzhzl8j0ldc1fj8wvm7fsy40000gn/T/122898852/gore_session.go:13: undefined: time
error: exit status 2
exit status 2
gore> :import "time"
gore> time
# command-line-arguments
/var/folders/mr/qvzhzl8j0ldc1fj8wvm7fsy40000gn/T/122898852/gore_session.go:13: undefined: time
error: exit status 2
exit status 2

**Comment by syohex** [comment]
`time` is package name. Can you see `time.Sunday`, `time.UnixDate` etc ?

```
% go version
go version go1.5.1 linux/amd64
% gore
gore version 0.2.5  :help for help
gore> :import time
gore> time.Tuesday
2
gore> time.ANSIC
"Mon Jan _2 15:04:05 2006"
gore> time.Sunday
0
gore> time.UnixDate
"Mon Jan _2 15:04:05 MST 2006"
```

**Comment by ches** [comment]
Was this perhaps an old version of Go? 1.5.1 gives a more useful error message:

```
gore> :import time
gore> time
# command-line-arguments
/var/folders/rn/jn2hxmmx7csbzj1ft7j7f3v40000gn/T/553716789/gore_session.go:13: use of package time without selector
error: exit status 2
exit status 2
```

**Comment by tejasmanohar** [comment]
This is solved

**Comment by tejasmanohar** [comment]
And yea it was an older version of Go, but haven't gotten a chance to test before/after yet... will do that tomorrorw and post here.
