### ISSUE TITLE
fmt.Println Executed Multiple Times

### ISSUE THREAD

**Issue by jdhenke** [motemen/gore#53]
```
$ go version
go version go1.5 darwin/amd64
$ gore
gore version 0.2.5  :help for help
gore> :import fmt
gore> fmt.Println("Yoo")
Yoo
4
<nil>
gore> n := 1
Yoo // <--- why is this printed?
1
```

**Comment by motemen** [comment]
Unfortunately this is [an expected behavior of gore](https://github.com/motemen/gore#faqcaveats), which invokes `go run` on each REPL input. It may seem misbehaving if the expressions involve I/O.

I'd love to hear any idea to solve this problem, thanks.
