### ISSUE TITLE
Can't execute some expressions, and can't complete on some keywords

### ISSUE THREAD

**Issue by stardiviner** [motemen/gore#56]
Can't execute some expressions like:

- `import "fmt"`

Can't complete on some keywords, like:
- `import`
- `func`
Seems don't complete all Go keywords.

**Comment by syohex** [comment]
You should use `:import` REPL command instead of `import` statement. You can use package completion in `:import` command. In `:import`, you don't need quote around package name.

**Comment by stardiviner** [comment]
@syohex , thanks, BTW, do you know why gore don't complete Go keywords like `func` etc?

**Comment by syohex** [comment]
Sorry I don't know. I suppose gocode does not support keyword completion feature.
