### ISSUE TITLE
Question: Screenrecording

### ISSUE THREAD

**Issue by whoisstan** [motemen/gore#6]
Just a quick question, what tool did you use to record the terminal interaction? Looks awesome.

**Comment by motemen** [comment]
Thanks, it was taken by [LICEcap](http://www.cockos.com/licecap/) with [cho45/KeyCast](https://github.com/cho45/KeyCast).

**Comment by motemen** [comment]
Seems like kind of FAQ, included in the README in  acb226f9fa7532a0e68806547796af4448c6152c.
