### ISSUE TITLE
String length error

### ISSUE THREAD

**Issue by willfaught** [motemen/gore#61]
Note that I entered a `}` after `if i == 5 { break }` but for some reason that's not shown in the output.

```
$ gore -autoimport
gore version 0.2.5  :help for help
gore> for i := 0; i < 50000; i++ {
.....     if err := exec.Command("./myscript", fmt.Sprintf("name+%v@domain.com", i), fmt.Sprintf("password-%v, i), fmt.Sprintf("first-%v", i), fmt.Sprintf("last-%v", i)).Run(); err != nil {
.....     fmt.Println("Error: %v: %v", i, err)
..... }
..... if i == 5 { break }
panic: runtime error: makeslice: len out of range

goroutine 1 [running]:
strings.Repeat(0x35e968, 0x4, 0xffffffffffffffff, 0x0, 0x0)
    /usr/local/Cellar/go/1.5.1/libexec/src/strings/strings.go:464 +0x5f
main.(*contLiner).promptString(0x8205f1880, 0x0, 0x0)
    /Users/Me/src/github.com/motemen/gore/liner.go:33 +0x54
main.(*contLiner).Reindent(0x8205f1880)
    /Users/Me/src/github.com/motemen/gore/liner.go:81 +0xfc
main.main()
    /Users/Me/src/github.com/motemen/gore/main.go:119 +0xb16

goroutine 5 [syscall]:
os/signal.loop()
    /usr/local/Cellar/go/1.5.1/libexec/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
    /usr/local/Cellar/go/1.5.1/libexec/src/os/signal/signal_unix.go:28 +0x37

goroutine 6 [select, locked to thread]:
runtime.gopark(0x427130, 0x82061c728, 0x362798, 0x6, 0x3f118, 0x2)
    /usr/local/Cellar/go/1.5.1/libexec/src/runtime/proc.go:185 +0x163
runtime.selectgoImpl(0x82061c728, 0x0, 0x18)
    /usr/local/Cellar/go/1.5.1/libexec/src/runtime/select.go:392 +0xa64
runtime.selectgo(0x82061c728)
    /usr/local/Cellar/go/1.5.1/libexec/src/runtime/select.go:212 +0x12
runtime.ensureSigM.func1()
    /usr/local/Cellar/go/1.5.1/libexec/src/runtime/signal1_unix.go:227 +0x323
runtime.goexit()
    /usr/local/Cellar/go/1.5.1/libexec/src/runtime/asm_amd64.s:1696 +0x1
```

**Comment by syohex** [comment]
You missed double quote at `fmt.Sprintf("password-%v, i),`. First argument string is not closed by double quote. If it is correct, there is no error.

**Comment by willfaught** [comment]
Should it really be causing a runtime panic in strings? I've never even seen that panic before. An "invalid syntax" error and the program not crashing would be more helpful.

**Comment by syohex** [comment]
Then `strings.Repeat("    ", -1)` is called and runtime error is occurred.

**Comment by willfaught** [comment]
@syohex I'm sorry, I didn't follow what you meant about Repeat. Are you saying Repeat is called with those args because of the input, and that's expected?

It seems to me that the program should anticipate syntax and other programming errors and be resilient enough to not crash when that happens. It's asking a lot to expect programmers to enter perfect code every time.

**Comment by syohex** [comment]
>  I'm sorry, I didn't follow what you meant about Repeat. Are you saying Repeat is called with those args because of the input, and that's expected?

`strings.Repeat` is called for inserting indentation.

**Comment by willfaught** [comment]
Sure, I can see that; but what I'm saying is that gore should instead prevent a negative argument and instead tell the user the input was invalid.
