### ISSUE TITLE
Newer version of go tools breaks gore

### ISSUE THREAD

**Issue by MadhATTER6** [motemen/gore#63]
gore uses the deprecated types package from x/tools, and as of [this commit](github.com/golang/tools/commit/adaaa07) types has been removed from x/tools. Most of the functionality is in the std lib as go/types, but some of it has been split out into go/importer. I tried to port over the code myself, but I don't understand it well enough and I don't have the time right now to dive into it.

Also x/tools/gcimporter has been deleted as well, maybe this can be swapped out with x/tools/gcimporter15? It seemed to compile fine when I made that change, but I don't know if the semantics changed.

This issue goes hand-in-hand with [this pull-request for go-quickfix](github.com/motemen/go-quickfix/pull/4)

**Comment by metakermit** [comment]
I think I might be experiencing this issue as well. I freshly installed Go (`brew install go`) and trying to install the package yields:

```
➜  go go get -u github.com/motemen/gore
package golang.org/x/tools/go/gcimporter: cannot find package "golang.org/x/tools/go/gcimporter" in any of:
	/usr/local/Cellar/go/1.6/libexec/src/golang.org/x/tools/go/gcimporter (from $GOROOT)
	/Users/kermit/.go/src/golang.org/x/tools/go/gcimporter (from $GOPATH)
package golang.org/x/tools/go/types: no buildable Go source files in /Users/kermit/.go/src/golang.org/x/tools/go/types
```

My Go version is `go1.6 darwin/amd64`.

**Comment by exarkun** [comment]
Also encountered this on go1.6 linux/amd64:

```
$ go get -u github.com/motemen/gore
package golang.org/x/tools/go/gcimporter: cannot find package "golang.org/x/tools/go/gcimporter" in any of:
        /usr/lib/go/src/golang.org/x/tools/go/gcimporter (from $GOROOT)
        /golang/src/golang.org/x/tools/go/gcimporter (from $GOPATH)
package golang.org/x/tools/go/types: no buildable Go source files in /golang/src/golang.org/x/tools/go/types
```

**Comment by syohex** [comment]
#64 has been merged. Could you retry to install ?

**Comment by metakermit** [comment]
Works now, thanks!

```
➜  go go get -u github.com/motemen/gore
➜  go gore
gore version 0.2.5  :help for help
gore> 1+1
2
gore>
```

**Comment by MadhATTER6** [comment]
Yes, it works for me now as well.
