### ISSUE TITLE
Pacakage "gcimporter" not found

### ISSUE THREAD

**Issue by romanvbabenko** [motemen/gore#65]
Does not work for me: 

```go get -u github.com/motemen/gore``` causes this

```
cannot find package "golang.org/x/tools/go/gcimporter" in any of: ...
```

**Comment by syohex** [comment]
This is duplicated to #63. And PR is #64.

**Comment by syohex** [comment]
#64 has been merged. Could you retry to install ?

**Comment by romanvbabenko** [comment]
It works. Thanks
