### ISSUE TITLE
Gore doesn't report panics from other go routines

### ISSUE THREAD

**Issue by JoeReid** [motemen/gore#66]
Starting a routine that panics immediately continues with no indication.

```
$ gore
gore version 0.2.5  :help for help
gore> go func(){panic("some panic")}()
gore>
```

Or indeed invoking the panic directly.

```
$ gore
gore version 0.2.5  :help for help
gore> go panic("some panic")
gore>
```

The playground (or a normal go program) will halt execution in this event [example](https://play.golang.org/p/hVLgkzerWW).

Exiting would clearly not be an ideal solution for a REPL, but some kind of notification to the user that a panic has occurred would be beneficial.

**Comment by syohex** [comment]
Your example is same as following code(`test.go`). `go run test.go` may not report anything because main go routine exits before another goroutine running.

```go
package main

func main() {
        go panic("some panic")
}
```

`gore` report panic of other go routine if main go routine wait until other go routine panics.

```
% gore
gore version 0.2.5  :help for help
gore> :import time
gore> go panic("some panic"); time.Sleep(time.Second)
panic: some panic

goroutine 5 [running]:
panic(0x49f060, 0xc82000a2e0)
	/opt/go/src/runtime/panic.go:464 +0x3e6
created by main.main
	/tmp/037141220/gore_session.go:13 +0x7b
exit status 2
error: exit status 1
exit status 1
```
