### ISSUE TITLE
Import fails to find pacakge that exists

### ISSUE THREAD

**Issue by ashb** [motemen/gore#68]
Really loving gore so far, but found an odd bug.

If I run this command first: `go get github.com/leanovate/gopter` then try the following gore commands:

`:import github.com/leanovate/gopter` (this one works).

`:import github.com/leanovate/gopter/gen` This one fails with `error: import: can't find import: github.com/leanovate/gopter/prop`

Double checking that it exists:

```
$ grep 'package prop' $GOPATH/src/github.com/leanovate/gopter/prop/*
/Users/ash/code/go/src/github.com/leanovate/gopter/prop/check_condition_func.go:package prop
/Users/ash/code/go/src/github.com/leanovate/gopter/prop/check_condition_func_test.go:package prop
/Users/ash/code/go/src/github.com/leanovate/gopter/prop/convert_result.go:package prop
```

Have I done something stupid? Is this a bug in gopter? I got the package name from the Invalidconcat example here: https://godoc.org/github.com/leanovate/gopter/prop#example-package--Invalidconcat

**Comment by syohex** [comment]
You can avoid error by installing `github.com/leanovate/gopter/gen`.

```
% go get github.com/leanovate/gopter/gen
```

I suppose this caused by`go/importer`. `importer.Default().Import(path)` which is used in `gore` for importing package finds only under `$GOPATH/pkg`. `go get github.com/leanovate/gopter` builds only `$GOPATH/pkg/your_architecture/github.com/leanovate/gopter.a` and does not build `$GOPATH/pkg/your_architecture/github.com/leanovate/gopter/gen.a`. So you got such error.

**Comment by ashb** [comment]
I'm confused though - I can take the example gopter code and `go run` it fine. So what is `run`/`build` doing that gore is not?

**Comment by syohex** [comment]
`go run` compiles source code and run it. While `:import` of `gore` loads package object file(`*.a` file on Linux system), it does not compile source code and not generate object file. `:import` commands raises error if there is no object file. So you need to generate object file before using `:import` command.

**Comment by ashb** [comment]
Ahh right, that makes sense, thanks! I'm still kind of new to go. I managed to fix it via `go install github.com/leanovate/gopter/gen`

Is it possible that gore could notice that case and either run the install for me, or print a more understandable error message? I guess anything is possible, is it practical?

**Comment by syohex** [comment]
Yes it is possible. Code is here.

https://github.com/motemen/gore/blob/603106957dbb1f054a60be39c4bc0c84cc060e44/commands.go#L84-L88

**Comment by motemen** [comment]
Thanks both, yes it is the current behavior of gore to  require `:import`ed packages to be intalled, which causes such confusion. I think this could be fixed.

**Comment by zacacollier** [comment]
I was wrestling with this for a while and could only get it to work by `go get`ting the package I needed and then running `gore` **from my home directory**:

```
zac@lenovo ~ % go get github.com/aws/aws-sdk-go/aws/session
zac@lenovo ~ % gore
gore version 0.3.0  :help for help
gore> :import github.com/aws/aws-sdk-go/aws/session
gore> session.NewSession
(func(...*aws.Config) (*session.Session, error))(0x6efdb0)
gore>
```
@motemen I'd be happy to add this the README if you could provide a bit of context as to why this is the case?
