### ISSUE TITLE
"imported and not used" doesn't make sense for REPL usage

### ISSUE THREAD

**Issue by dbkaplun** [motemen/gore#71]
``` go
$ gore
gore version 0.2.6  :help for help
gore> :import foo.com/web/bar/client
gore> :import github.com/cactus/go-statsd-client/statsd
gore> stats, err := statsd.NewNoopClient()
# command-line-arguments
/var/folders/w5/78q6nz451l104zzfdljf13jxhmx2wt/T/410385164/gore_session.go:6: imported and not used: "foo.com/web/bar/client" as bar
error: exit status 2
exit status 2
gore> 
```

**Comment by ybank** [comment]
Strongly +1 for this feature, rather than a bug. In REPL developers mostly attempt several experiment and it does not make sense to statically checking either redundant or unnecessary imports here.

This might be hard to fix, though.

**Comment by dbkaplun** [comment]
One possible solution would be to import everything twice, once normally and once via [blank import](https://golang.org/doc/effective_go.html#blank_import). Doesn't seem too complicated but I am not familiar with gore's import handling mechanism.

**Comment by motemen** [comment]
gore already has a mechnism to detect unused imports and transform them to blank ones, so if it does not work this would be a bug. But I could not reproduce it.

```

**Comment by itchyny** [comment]
Closing because this is expected to work.

**Comment by tangxinfa** [comment]
This bug still exists:

$ gore
gore version 0.5.6  :help for help
gore> :import time
gore> :import fmt
gore> fmt.Printf("hello")
"time" imported and not used
gore>

**Comment by itchyny** [comment]
@tangxinfa Not reproducible with 0.5.7.
