### ISSUE TITLE
adding clean command

### ISSUE THREAD

**Issue by Lenskiy** [motemen/gore#73]
Would be great to have a _clean_ command, that would allow not to **restart** gore just to cleanup the current code in the main function.

**Comment by adelowo** [comment]
I should be able to implement this during the weekend

**Comment by adelowo** [comment]
@motemen Is this the same as the `reset` command [described here in source code](https://github.com/motemen/gore/blob/master/commands.go#L32) ?

**Comment by itchyny** [comment]
The `:clear` command is implemented.
