### ISSUE TITLE
writing a function in gore?

### ISSUE THREAD

**Issue by dtenenba** [motemen/gore#76]
I'm sure I'm missing something very obvious but I'm not sure how to write a multi-line function in gore:

```
[dtenenba@C02S72TRFVH8 ~]$ gore
gore version 0.2.6  :help for help
gore> func Foo() string {
.....     return "foo"
..... }
.....
```

How do I get out of `.....` land and back to the `gore>` prompt so I can call my function?
Same thing happens if I write the function as a one-liner:

```
[dtenenba@C02S72TRFVH8 ~]$ gore
gore version 0.2.6  :help for help
gore> func Foo() string { return "foo" }
.....
```

**Comment by c3mb0** [comment]
Not sure how complex your case gets, but you could assign your function to a variable (since functions are first class in Go) and use it like so:

```
Foo := func () string { return "foo" }
fmt.Println(Foo());
```

**Comment by dtenenba** [comment]
Thanks. But I am interested in knowing if what I initially tried to do is supported or not.
The README says "multiline inputs" is a feature of gore.

**Comment by idubinskiy** [comment]
@dtenenba The variable assignment form will let you write multiline functions.

```go
gore version 0.2.6  :help for help
gore> Foo := func() string {
.....     return "foo"
..... }
(func() string)(0x2180)
gore> Foo()
"foo"
```

BTW, looks like the named function declaration form doesn't work even for single-line functions:

```go
gore version 0.2.6  :help for help
gore> func Foo() string { return "foo" }
..... 
..... 
```

**Comment by idubinskiy** [comment]
The issue is that `gore` puts everything into the `main` function, and the function declaration form is only allowed at the top level, not inside other functions. I'm guessing it could be changed to detect those declarations (seems like they aren't even being parsed properly now, thus the issue with `.....`) and put them next to `main` instead of inside it. But it probably wouldn't be a trivial fix.

**Comment by itchyny** [comment]
The issue is resolved now.
