### ISSUE TITLE
Support multiple imports

### ISSUE THREAD

**Issue by adelowo** [motemen/gore#77]
Hi, i think the ability to import multiple packages on a single line would be a great addition.. Something like `:import time,fmt,encoding/json`. The separator here is a comma(`,`) but a space can be used too.

Thanks

**Comment by adelowo** [comment]
I have implemented this already, would submit a PR as soon as I get back to my laptop

**Comment by motemen** [comment]
Closing, https://github.com/motemen/gore/pull/78#issuecomment-335763071
